# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_LocationTotals.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmLocationTotals(object):
    def setupUi(self, frmLocationTotals):
        frmLocationTotals.setObjectName("frmLocationTotals")
        frmLocationTotals.resize(665, 580)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmLocationTotals.sizePolicy().hasHeightForWidth())
        frmLocationTotals.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_locationtotals.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmLocationTotals.setWindowIcon(icon)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(frmLocationTotals)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(frmLocationTotals)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 647, 562))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblLocation = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLocation.sizePolicy().hasHeightForWidth())
        self.lblLocation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblLocation.setFont(font)
        self.lblLocation.setObjectName("lblLocation")
        self.verticalLayout.addWidget(self.lblLocation)
        self.lblDateRange = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateRange.sizePolicy().hasHeightForWidth())
        self.lblDateRange.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblDateRange.setFont(font)
        self.lblDateRange.setObjectName("lblDateRange")
        self.verticalLayout.addWidget(self.lblDateRange)
        self.lblDetails = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDetails.sizePolicy().hasHeightForWidth())
        self.lblDetails.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblDetails.setFont(font)
        self.lblDetails.setObjectName("lblDetails")
        self.verticalLayout.addWidget(self.lblDetails)
        self.tabLocationTotals = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabLocationTotals.setObjectName("tabLocationTotals")
        self.tabRegionTotals = QtWidgets.QWidget()
        self.tabRegionTotals.setObjectName("tabRegionTotals")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabRegionTotals)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tblRegionTotals = QtWidgets.QTableWidget(self.tabRegionTotals)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblRegionTotals.sizePolicy().hasHeightForWidth())
        self.tblRegionTotals.setSizePolicy(sizePolicy)
        self.tblRegionTotals.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tblRegionTotals.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tblRegionTotals.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblRegionTotals.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblRegionTotals.setObjectName("tblRegionTotals")
        self.tblRegionTotals.setColumnCount(0)
        self.tblRegionTotals.setRowCount(0)
        self.tblRegionTotals.horizontalHeader().setVisible(False)
        self.tblRegionTotals.horizontalHeader().setHighlightSections(False)
        self.tblRegionTotals.verticalHeader().setVisible(False)
        self.tblRegionTotals.verticalHeader().setHighlightSections(False)
        self.verticalLayout_6.addWidget(self.tblRegionTotals)
        self.tabLocationTotals.addTab(self.tabRegionTotals, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tblCountryTotals = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblCountryTotals.sizePolicy().hasHeightForWidth())
        self.tblCountryTotals.setSizePolicy(sizePolicy)
        self.tblCountryTotals.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tblCountryTotals.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tblCountryTotals.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblCountryTotals.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblCountryTotals.setObjectName("tblCountryTotals")
        self.tblCountryTotals.setColumnCount(0)
        self.tblCountryTotals.setRowCount(0)
        self.tblCountryTotals.horizontalHeader().setVisible(False)
        self.tblCountryTotals.horizontalHeader().setHighlightSections(False)
        self.tblCountryTotals.verticalHeader().setVisible(False)
        self.tblCountryTotals.verticalHeader().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.tblCountryTotals)
        self.tabLocationTotals.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tblStateTotals = QtWidgets.QTableWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblStateTotals.sizePolicy().hasHeightForWidth())
        self.tblStateTotals.setSizePolicy(sizePolicy)
        self.tblStateTotals.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tblStateTotals.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblStateTotals.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblStateTotals.setObjectName("tblStateTotals")
        self.tblStateTotals.setColumnCount(0)
        self.tblStateTotals.setRowCount(0)
        self.tblStateTotals.horizontalHeader().setVisible(False)
        self.tblStateTotals.horizontalHeader().setSortIndicatorShown(True)
        self.tblStateTotals.verticalHeader().setVisible(False)
        self.tblStateTotals.verticalHeader().setHighlightSections(False)
        self.tblStateTotals.verticalHeader().setSortIndicatorShown(False)
        self.tblStateTotals.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.tblStateTotals)
        self.tabLocationTotals.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tblCountyTotals = QtWidgets.QTableWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblCountyTotals.sizePolicy().hasHeightForWidth())
        self.tblCountyTotals.setSizePolicy(sizePolicy)
        self.tblCountyTotals.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tblCountyTotals.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblCountyTotals.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblCountyTotals.setObjectName("tblCountyTotals")
        self.tblCountyTotals.setColumnCount(0)
        self.tblCountyTotals.setRowCount(0)
        self.tblCountyTotals.horizontalHeader().setVisible(False)
        self.tblCountyTotals.horizontalHeader().setSortIndicatorShown(True)
        self.tblCountyTotals.verticalHeader().setVisible(False)
        self.tblCountyTotals.verticalHeader().setHighlightSections(False)
        self.tblCountyTotals.verticalHeader().setSortIndicatorShown(False)
        self.tblCountyTotals.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tblCountyTotals)
        self.tabLocationTotals.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tblLocationTotals = QtWidgets.QTableWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblLocationTotals.sizePolicy().hasHeightForWidth())
        self.tblLocationTotals.setSizePolicy(sizePolicy)
        self.tblLocationTotals.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tblLocationTotals.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblLocationTotals.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblLocationTotals.setObjectName("tblLocationTotals")
        self.tblLocationTotals.setColumnCount(0)
        self.tblLocationTotals.setRowCount(0)
        self.tblLocationTotals.horizontalHeader().setVisible(False)
        self.tblLocationTotals.horizontalHeader().setSortIndicatorShown(True)
        self.tblLocationTotals.verticalHeader().setVisible(False)
        self.tblLocationTotals.verticalHeader().setHighlightSections(False)
        self.tblLocationTotals.verticalHeader().setSortIndicatorShown(False)
        self.tblLocationTotals.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_5.addWidget(self.tblLocationTotals)
        self.tabLocationTotals.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabLocationTotals)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.actionSetLocationFilter = QtWidgets.QAction(frmLocationTotals)
        self.actionSetLocationFilter.setObjectName("actionSetLocationFilter")
        self.actionSetCountryFilter = QtWidgets.QAction(frmLocationTotals)
        self.actionSetCountryFilter.setObjectName("actionSetCountryFilter")
        self.actionSetStateFilter = QtWidgets.QAction(frmLocationTotals)
        self.actionSetStateFilter.setObjectName("actionSetStateFilter")
        self.actionSetCountyFilter = QtWidgets.QAction(frmLocationTotals)
        self.actionSetCountyFilter.setObjectName("actionSetCountyFilter")

        self.retranslateUi(frmLocationTotals)
        self.tabLocationTotals.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmLocationTotals)

    def retranslateUi(self, frmLocationTotals):
        _translate = QtCore.QCoreApplication.translate
        frmLocationTotals.setWindowTitle(_translate("frmLocationTotals", "Location Totals"))
        self.lblLocation.setText(_translate("frmLocationTotals", "Location"))
        self.lblDateRange.setText(_translate("frmLocationTotals", "Date Range"))
        self.lblDetails.setText(_translate("frmLocationTotals", "Details Label"))
        self.tblRegionTotals.setSortingEnabled(True)
        self.tabLocationTotals.setTabText(self.tabLocationTotals.indexOf(self.tabRegionTotals), _translate("frmLocationTotals", "Region Totals"))
        self.tblCountryTotals.setSortingEnabled(True)
        self.tabLocationTotals.setTabText(self.tabLocationTotals.indexOf(self.tab), _translate("frmLocationTotals", "Country Totals"))
        self.tblStateTotals.setSortingEnabled(True)
        self.tabLocationTotals.setTabText(self.tabLocationTotals.indexOf(self.tab_3), _translate("frmLocationTotals", "State Totals"))
        self.tblCountyTotals.setSortingEnabled(True)
        self.tabLocationTotals.setTabText(self.tabLocationTotals.indexOf(self.tab_4), _translate("frmLocationTotals", "County Totals"))
        self.tblLocationTotals.setSortingEnabled(True)
        self.tabLocationTotals.setTabText(self.tabLocationTotals.indexOf(self.tab_2), _translate("frmLocationTotals", "Location Totals"))
        self.actionSetLocationFilter.setText(_translate("frmLocationTotals", "Set Filter to Location"))
        self.actionSetCountryFilter.setText(_translate("frmLocationTotals", "Set Filter to Country"))
        self.actionSetStateFilter.setText(_translate("frmLocationTotals", "Set Filter to State"))
        self.actionSetCountyFilter.setText(_translate("frmLocationTotals", "Set Filter to County"))
import icons_rc
