# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_MDIMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1262, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(110, 115, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName("mdiArea")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1262, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuReports = QtWidgets.QMenu(self.menuBar)
        self.menuReports.setObjectName("menuReports")
        self.menuWindows = QtWidgets.QMenu(self.menuBar)
        self.menuWindows.setObjectName("menuWindows")
        self.menuMap = QtWidgets.QMenu(self.menuBar)
        self.menuMap.setObjectName("menuMap")
        self.menuLists = QtWidgets.QMenu(self.menuBar)
        self.menuLists.setObjectName("menuLists")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFilter = QtWidgets.QMenu(self.menuBar)
        self.menuFilter.setObjectName("menuFilter")
        self.menuPhotos = QtWidgets.QMenu(self.menuBar)
        self.menuPhotos.setObjectName("menuPhotos")
        self.menuChoropleths = QtWidgets.QMenu(self.menuBar)
        self.menuChoropleths.setObjectName("menuChoropleths")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.dckFilter = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dckFilter.sizePolicy().hasHeightForWidth())
        self.dckFilter.setSizePolicy(sizePolicy)
        self.dckFilter.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dckFilter.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dckFilter.setObjectName("dckFilter")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrFilter = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrFilter.setMinimumSize(QtCore.QSize(0, 0))
        self.scrFilter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrFilter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrFilter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrFilter.setLineWidth(0)
        self.scrFilter.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrFilter.setWidgetResizable(True)
        self.scrFilter.setObjectName("scrFilter")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 179, 859))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, -1)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frmFilter = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmFilter.sizePolicy().hasHeightForWidth())
        self.frmFilter.setSizePolicy(sizePolicy)
        self.frmFilter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmFilter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmFilter.setObjectName("frmFilter")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frmFilter)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblCountries_2 = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCountries_2.setFont(font)
        self.lblCountries_2.setObjectName("lblCountries_2")
        self.verticalLayout.addWidget(self.lblCountries_2)
        self.cboRegions = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboRegions.sizePolicy().hasHeightForWidth())
        self.cboRegions.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cboRegions.setFont(font)
        self.cboRegions.setObjectName("cboRegions")
        self.verticalLayout.addWidget(self.cboRegions)
        self.lblCountries = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCountries.setFont(font)
        self.lblCountries.setObjectName("lblCountries")
        self.verticalLayout.addWidget(self.lblCountries)
        self.cboCountries = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboCountries.sizePolicy().hasHeightForWidth())
        self.cboCountries.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cboCountries.setFont(font)
        self.cboCountries.setObjectName("cboCountries")
        self.verticalLayout.addWidget(self.cboCountries)
        self.lblStates = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblStates.setFont(font)
        self.lblStates.setObjectName("lblStates")
        self.verticalLayout.addWidget(self.lblStates)
        self.cboStates = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStates.sizePolicy().hasHeightForWidth())
        self.cboStates.setSizePolicy(sizePolicy)
        self.cboStates.setObjectName("cboStates")
        self.verticalLayout.addWidget(self.cboStates)
        self.lblCounties = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCounties.setFont(font)
        self.lblCounties.setObjectName("lblCounties")
        self.verticalLayout.addWidget(self.lblCounties)
        self.cboCounties = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboCounties.sizePolicy().hasHeightForWidth())
        self.cboCounties.setSizePolicy(sizePolicy)
        self.cboCounties.setObjectName("cboCounties")
        self.verticalLayout.addWidget(self.cboCounties)
        self.lblLocations = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLocations.setFont(font)
        self.lblLocations.setObjectName("lblLocations")
        self.verticalLayout.addWidget(self.lblLocations)
        self.cboLocations = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboLocations.sizePolicy().hasHeightForWidth())
        self.cboLocations.setSizePolicy(sizePolicy)
        self.cboLocations.setObjectName("cboLocations")
        self.verticalLayout.addWidget(self.cboLocations)
        self.lblOrders = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblOrders.setFont(font)
        self.lblOrders.setObjectName("lblOrders")
        self.verticalLayout.addWidget(self.lblOrders)
        self.cboOrders = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboOrders.sizePolicy().hasHeightForWidth())
        self.cboOrders.setSizePolicy(sizePolicy)
        self.cboOrders.setObjectName("cboOrders")
        self.verticalLayout.addWidget(self.cboOrders)
        self.lblFamilies = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFamilies.setFont(font)
        self.lblFamilies.setObjectName("lblFamilies")
        self.verticalLayout.addWidget(self.lblFamilies)
        self.cboFamilies = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFamilies.sizePolicy().hasHeightForWidth())
        self.cboFamilies.setSizePolicy(sizePolicy)
        self.cboFamilies.setObjectName("cboFamilies")
        self.verticalLayout.addWidget(self.cboFamilies)
        self.lblSpecies = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSpecies.setFont(font)
        self.lblSpecies.setObjectName("lblSpecies")
        self.verticalLayout.addWidget(self.lblSpecies)
        self.cboSpecies = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSpecies.sizePolicy().hasHeightForWidth())
        self.cboSpecies.setSizePolicy(sizePolicy)
        self.cboSpecies.setObjectName("cboSpecies")
        self.verticalLayout.addWidget(self.cboSpecies)
        self.lblCommonNameSearch = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCommonNameSearch.setFont(font)
        self.lblCommonNameSearch.setObjectName("lblCommonNameSearch")
        self.verticalLayout.addWidget(self.lblCommonNameSearch)
        self.txtCommonNameSearch = QtWidgets.QLineEdit(self.frmFilter)
        self.txtCommonNameSearch.setObjectName("txtCommonNameSearch")
        self.verticalLayout.addWidget(self.txtCommonNameSearch)
        self.lblEndSeasonalRange_2 = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblEndSeasonalRange_2.setFont(font)
        self.lblEndSeasonalRange_2.setObjectName("lblEndSeasonalRange_2")
        self.verticalLayout.addWidget(self.lblEndSeasonalRange_2)
        self.cboDateOptions = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboDateOptions.sizePolicy().hasHeightForWidth())
        self.cboDateOptions.setSizePolicy(sizePolicy)
        self.cboDateOptions.setObjectName("cboDateOptions")
        self.verticalLayout.addWidget(self.cboDateOptions)
        self.lblStartDate = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblStartDate.setFont(font)
        self.lblStartDate.setObjectName("lblStartDate")
        self.verticalLayout.addWidget(self.lblStartDate)
        self.calStartDate = QtWidgets.QDateTimeEdit(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calStartDate.sizePolicy().hasHeightForWidth())
        self.calStartDate.setSizePolicy(sizePolicy)
        self.calStartDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 2, 1), QtCore.QTime(0, 0, 0)))
        self.calStartDate.setCalendarPopup(True)
        self.calStartDate.setObjectName("calStartDate")
        self.verticalLayout.addWidget(self.calStartDate)
        self.lblEndDate = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblEndDate.setFont(font)
        self.lblEndDate.setObjectName("lblEndDate")
        self.verticalLayout.addWidget(self.lblEndDate)
        self.calEndDate = QtWidgets.QDateTimeEdit(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calEndDate.sizePolicy().hasHeightForWidth())
        self.calEndDate.setSizePolicy(sizePolicy)
        self.calEndDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 2, 1), QtCore.QTime(0, 0, 0)))
        self.calEndDate.setCalendarPopup(True)
        self.calEndDate.setObjectName("calEndDate")
        self.verticalLayout.addWidget(self.calEndDate)
        self.lblEndSeasonalRange_3 = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblEndSeasonalRange_3.setFont(font)
        self.lblEndSeasonalRange_3.setObjectName("lblEndSeasonalRange_3")
        self.verticalLayout.addWidget(self.lblEndSeasonalRange_3)
        self.cboSeasonalRangeOptions = QtWidgets.QComboBox(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSeasonalRangeOptions.sizePolicy().hasHeightForWidth())
        self.cboSeasonalRangeOptions.setSizePolicy(sizePolicy)
        self.cboSeasonalRangeOptions.setObjectName("cboSeasonalRangeOptions")
        self.verticalLayout.addWidget(self.cboSeasonalRangeOptions)
        self.lblStartSeasonalRange = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblStartSeasonalRange.setFont(font)
        self.lblStartSeasonalRange.setObjectName("lblStartSeasonalRange")
        self.verticalLayout.addWidget(self.lblStartSeasonalRange)
        self.frmStartSeasonalRange = QtWidgets.QFrame(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmStartSeasonalRange.sizePolicy().hasHeightForWidth())
        self.frmStartSeasonalRange.setSizePolicy(sizePolicy)
        self.frmStartSeasonalRange.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmStartSeasonalRange.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmStartSeasonalRange.setLineWidth(0)
        self.frmStartSeasonalRange.setObjectName("frmStartSeasonalRange")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frmStartSeasonalRange)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cboStartSeasonalRangeMonth = QtWidgets.QComboBox(self.frmStartSeasonalRange)
        self.cboStartSeasonalRangeMonth.setObjectName("cboStartSeasonalRangeMonth")
        self.horizontalLayout.addWidget(self.cboStartSeasonalRangeMonth)
        self.cboStartSeasonalRangeDate = QtWidgets.QComboBox(self.frmStartSeasonalRange)
        self.cboStartSeasonalRangeDate.setObjectName("cboStartSeasonalRangeDate")
        self.horizontalLayout.addWidget(self.cboStartSeasonalRangeDate)
        self.verticalLayout.addWidget(self.frmStartSeasonalRange)
        self.lblEndSeasonalRange = QtWidgets.QLabel(self.frmFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblEndSeasonalRange.setFont(font)
        self.lblEndSeasonalRange.setObjectName("lblEndSeasonalRange")
        self.verticalLayout.addWidget(self.lblEndSeasonalRange)
        self.frmEndSeasonalRange = QtWidgets.QFrame(self.frmFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmEndSeasonalRange.sizePolicy().hasHeightForWidth())
        self.frmEndSeasonalRange.setSizePolicy(sizePolicy)
        self.frmEndSeasonalRange.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmEndSeasonalRange.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmEndSeasonalRange.setLineWidth(0)
        self.frmEndSeasonalRange.setObjectName("frmEndSeasonalRange")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmEndSeasonalRange)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cboEndSeasonalRangeMonth = QtWidgets.QComboBox(self.frmEndSeasonalRange)
        self.cboEndSeasonalRangeMonth.setObjectName("cboEndSeasonalRangeMonth")
        self.horizontalLayout_2.addWidget(self.cboEndSeasonalRangeMonth)
        self.cboEndSeasonalRangeDate = QtWidgets.QComboBox(self.frmEndSeasonalRange)
        self.cboEndSeasonalRangeDate.setObjectName("cboEndSeasonalRangeDate")
        self.horizontalLayout_2.addWidget(self.cboEndSeasonalRangeDate)
        self.verticalLayout.addWidget(self.frmEndSeasonalRange)
        self.verticalLayout_2.addWidget(self.frmFilter, 0, QtCore.Qt.AlignTop)
        self.scrFilter.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrFilter)
        self.dckFilter.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dckFilter)
        self.dckPhotoFilter = QtWidgets.QDockWidget(MainWindow)
        self.dckPhotoFilter.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dckPhotoFilter.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dckPhotoFilter.setObjectName("dckPhotoFilter")
        self.dockPhotoWidgetContents = QtWidgets.QWidget()
        self.dockPhotoWidgetContents.setObjectName("dockPhotoWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockPhotoWidgetContents)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrPhotoFilter = QtWidgets.QScrollArea(self.dockPhotoWidgetContents)
        self.scrPhotoFilter.setMinimumSize(QtCore.QSize(0, 0))
        self.scrPhotoFilter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrPhotoFilter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrPhotoFilter.setLineWidth(0)
        self.scrPhotoFilter.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrPhotoFilter.setWidgetResizable(True)
        self.scrPhotoFilter.setObjectName("scrPhotoFilter")
        self.scrollAreaPhotoWidgetContents = QtWidgets.QWidget()
        self.scrollAreaPhotoWidgetContents.setGeometry(QtCore.QRect(0, 0, 190, 440))
        self.scrollAreaPhotoWidgetContents.setObjectName("scrollAreaPhotoWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaPhotoWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frmPhotoFilter = QtWidgets.QFrame(self.scrollAreaPhotoWidgetContents)
        self.frmPhotoFilter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmPhotoFilter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmPhotoFilter.setObjectName("frmPhotoFilter")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frmPhotoFilter)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblSighting = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSighting.setFont(font)
        self.lblSighting.setObjectName("lblSighting")
        self.verticalLayout_6.addWidget(self.lblSighting)
        self.frmRatingRange = QtWidgets.QFrame(self.frmPhotoFilter)
        self.frmRatingRange.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmRatingRange.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmRatingRange.setLineWidth(0)
        self.frmRatingRange.setObjectName("frmRatingRange")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frmRatingRange)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cboStartRatingRange = QtWidgets.QComboBox(self.frmRatingRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStartRatingRange.sizePolicy().hasHeightForWidth())
        self.cboStartRatingRange.setSizePolicy(sizePolicy)
        self.cboStartRatingRange.setObjectName("cboStartRatingRange")
        self.horizontalLayout_5.addWidget(self.cboStartRatingRange)
        self.cboEndRatingRange = QtWidgets.QComboBox(self.frmRatingRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEndRatingRange.sizePolicy().hasHeightForWidth())
        self.cboEndRatingRange.setSizePolicy(sizePolicy)
        self.cboEndRatingRange.setObjectName("cboEndRatingRange")
        self.horizontalLayout_5.addWidget(self.cboEndRatingRange)
        self.verticalLayout_6.addWidget(self.frmRatingRange)
        self.lblSpeciesHasPhoto = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSpeciesHasPhoto.setFont(font)
        self.lblSpeciesHasPhoto.setObjectName("lblSpeciesHasPhoto")
        self.verticalLayout_6.addWidget(self.lblSpeciesHasPhoto)
        self.cboSpeciesHasPhoto = QtWidgets.QComboBox(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cboSpeciesHasPhoto.setFont(font)
        self.cboSpeciesHasPhoto.setObjectName("cboSpeciesHasPhoto")
        self.verticalLayout_6.addWidget(self.cboSpeciesHasPhoto)
        self.lblCamera = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCamera.setFont(font)
        self.lblCamera.setObjectName("lblCamera")
        self.verticalLayout_6.addWidget(self.lblCamera)
        self.cboCamera = QtWidgets.QComboBox(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cboCamera.setFont(font)
        self.cboCamera.setObjectName("cboCamera")
        self.verticalLayout_6.addWidget(self.cboCamera)
        self.lblLens = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLens.setFont(font)
        self.lblLens.setObjectName("lblLens")
        self.verticalLayout_6.addWidget(self.lblLens)
        self.cboLens = QtWidgets.QComboBox(self.frmPhotoFilter)
        self.cboLens.setObjectName("cboLens")
        self.verticalLayout_6.addWidget(self.cboLens)
        self.lblShutterSpeedRange = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblShutterSpeedRange.setFont(font)
        self.lblShutterSpeedRange.setObjectName("lblShutterSpeedRange")
        self.verticalLayout_6.addWidget(self.lblShutterSpeedRange)
        self.frmShutterSpeedRange = QtWidgets.QFrame(self.frmPhotoFilter)
        self.frmShutterSpeedRange.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmShutterSpeedRange.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmShutterSpeedRange.setLineWidth(0)
        self.frmShutterSpeedRange.setObjectName("frmShutterSpeedRange")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frmShutterSpeedRange)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cboStartShutterSpeedRange = QtWidgets.QComboBox(self.frmShutterSpeedRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStartShutterSpeedRange.sizePolicy().hasHeightForWidth())
        self.cboStartShutterSpeedRange.setSizePolicy(sizePolicy)
        self.cboStartShutterSpeedRange.setObjectName("cboStartShutterSpeedRange")
        self.horizontalLayout_3.addWidget(self.cboStartShutterSpeedRange)
        self.cboEndShutterSpeedRange = QtWidgets.QComboBox(self.frmShutterSpeedRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEndShutterSpeedRange.sizePolicy().hasHeightForWidth())
        self.cboEndShutterSpeedRange.setSizePolicy(sizePolicy)
        self.cboEndShutterSpeedRange.setObjectName("cboEndShutterSpeedRange")
        self.horizontalLayout_3.addWidget(self.cboEndShutterSpeedRange)
        self.verticalLayout_6.addWidget(self.frmShutterSpeedRange)
        self.lblApertureRange = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblApertureRange.setFont(font)
        self.lblApertureRange.setObjectName("lblApertureRange")
        self.verticalLayout_6.addWidget(self.lblApertureRange)
        self.frmApertureRange = QtWidgets.QFrame(self.frmPhotoFilter)
        self.frmApertureRange.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmApertureRange.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmApertureRange.setLineWidth(0)
        self.frmApertureRange.setObjectName("frmApertureRange")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frmApertureRange)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cboStartApertureRange = QtWidgets.QComboBox(self.frmApertureRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStartApertureRange.sizePolicy().hasHeightForWidth())
        self.cboStartApertureRange.setSizePolicy(sizePolicy)
        self.cboStartApertureRange.setObjectName("cboStartApertureRange")
        self.horizontalLayout_4.addWidget(self.cboStartApertureRange)
        self.cboEndApertureRange = QtWidgets.QComboBox(self.frmApertureRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEndApertureRange.sizePolicy().hasHeightForWidth())
        self.cboEndApertureRange.setSizePolicy(sizePolicy)
        self.cboEndApertureRange.setObjectName("cboEndApertureRange")
        self.horizontalLayout_4.addWidget(self.cboEndApertureRange)
        self.verticalLayout_6.addWidget(self.frmApertureRange)
        self.lblFocalLengthRange = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFocalLengthRange.setFont(font)
        self.lblFocalLengthRange.setObjectName("lblFocalLengthRange")
        self.verticalLayout_6.addWidget(self.lblFocalLengthRange)
        self.frmFocalLengthRange = QtWidgets.QFrame(self.frmPhotoFilter)
        self.frmFocalLengthRange.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmFocalLengthRange.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmFocalLengthRange.setLineWidth(0)
        self.frmFocalLengthRange.setObjectName("frmFocalLengthRange")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frmFocalLengthRange)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cboStartFocalLengthRange = QtWidgets.QComboBox(self.frmFocalLengthRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStartFocalLengthRange.sizePolicy().hasHeightForWidth())
        self.cboStartFocalLengthRange.setSizePolicy(sizePolicy)
        self.cboStartFocalLengthRange.setObjectName("cboStartFocalLengthRange")
        self.horizontalLayout_7.addWidget(self.cboStartFocalLengthRange)
        self.cboEndFocalLengthRange = QtWidgets.QComboBox(self.frmFocalLengthRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEndFocalLengthRange.sizePolicy().hasHeightForWidth())
        self.cboEndFocalLengthRange.setSizePolicy(sizePolicy)
        self.cboEndFocalLengthRange.setObjectName("cboEndFocalLengthRange")
        self.horizontalLayout_7.addWidget(self.cboEndFocalLengthRange)
        self.verticalLayout_6.addWidget(self.frmFocalLengthRange)
        self.lblISORange = QtWidgets.QLabel(self.frmPhotoFilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblISORange.setFont(font)
        self.lblISORange.setObjectName("lblISORange")
        self.verticalLayout_6.addWidget(self.lblISORange)
        self.frmIsoRange = QtWidgets.QFrame(self.frmPhotoFilter)
        self.frmIsoRange.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmIsoRange.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmIsoRange.setLineWidth(0)
        self.frmIsoRange.setObjectName("frmIsoRange")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frmIsoRange)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cboStartIsoRange = QtWidgets.QComboBox(self.frmIsoRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStartIsoRange.sizePolicy().hasHeightForWidth())
        self.cboStartIsoRange.setSizePolicy(sizePolicy)
        self.cboStartIsoRange.setObjectName("cboStartIsoRange")
        self.horizontalLayout_6.addWidget(self.cboStartIsoRange)
        self.cboEndIsoRange = QtWidgets.QComboBox(self.frmIsoRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEndIsoRange.sizePolicy().hasHeightForWidth())
        self.cboEndIsoRange.setSizePolicy(sizePolicy)
        self.cboEndIsoRange.setObjectName("cboEndIsoRange")
        self.horizontalLayout_6.addWidget(self.cboEndIsoRange)
        self.verticalLayout_6.addWidget(self.frmIsoRange)
        self.verticalLayout_5.addWidget(self.frmPhotoFilter)
        self.scrPhotoFilter.setWidget(self.scrollAreaPhotoWidgetContents)
        self.verticalLayout_4.addWidget(self.scrPhotoFilter, 0, QtCore.Qt.AlignTop)
        self.dckPhotoFilter.setWidget(self.dockPhotoWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dckPhotoFilter)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDateTotals = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon_datetotals.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDateTotals.setIcon(icon1)
        self.actionDateTotals.setObjectName("actionDateTotals")
        self.actionLocationTotals = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon_locationtotals.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLocationTotals.setIcon(icon2)
        self.actionLocationTotals.setObjectName("actionLocationTotals")
        self.actionTileWindows = QtWidgets.QAction(MainWindow)
        self.actionTileWindows.setObjectName("actionTileWindows")
        self.actionCloseAllWindows = QtWidgets.QAction(MainWindow)
        self.actionCloseAllWindows.setObjectName("actionCloseAllWindows")
        self.actionCompareLists = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon_compare.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompareLists.setIcon(icon3)
        self.actionCompareLists.setObjectName("actionCompareLists")
        self.actionCascade = QtWidgets.QAction(MainWindow)
        self.actionCascade.setObjectName("actionCascade")
        self.actionSpecies = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon_bird.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpecies.setIcon(icon4)
        self.actionSpecies.setObjectName("actionSpecies")
        self.actionLocations = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon_location.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLocations.setIcon(icon5)
        self.actionLocations.setObjectName("actionLocations")
        self.actionChecklists = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon_checklists.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChecklists.setIcon(icon6)
        self.actionChecklists.setObjectName("actionChecklists")
        self.actionBigReport = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon_tripreport.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBigReport.setIcon(icon7)
        self.actionBigReport.setObjectName("actionBigReport")
        self.actionFind = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon_find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind.setIcon(icon8)
        self.actionFind.setObjectName("actionFind")
        self.actionFamilies = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon_families.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFamilies.setIcon(icon9)
        self.actionFamilies.setObjectName("actionFamilies")
        self.actionMap = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon_map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMap.setIcon(icon10)
        self.actionMap.setObjectName("actionMap")
        self.actionCreatePDF = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon_pdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreatePDF.setIcon(icon11)
        self.actionCreatePDF.setObjectName("actionCreatePDF")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon_print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon12)
        self.actionPrint.setObjectName("actionPrint")
        self.actionAboutLapwing = QtWidgets.QAction(MainWindow)
        self.actionAboutLapwing.setObjectName("actionAboutLapwing")
        self.actionShowStandardFilter = QtWidgets.QAction(MainWindow)
        self.actionShowStandardFilter.setObjectName("actionShowStandardFilter")
        self.actionHideStandardFilter = QtWidgets.QAction(MainWindow)
        self.actionHideStandardFilter.setObjectName("actionHideStandardFilter")
        self.actionClearAllFilters = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon_filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearAllFilters.setIcon(icon13)
        self.actionClearAllFilters.setObjectName("actionClearAllFilters")
        self.actionSetPhotoFolder = QtWidgets.QAction(MainWindow)
        self.actionSetPhotoFolder.setObjectName("actionSetPhotoFolder")
        self.actionPhotos = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon_camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPhotos.setIcon(icon14)
        self.actionPhotos.setObjectName("actionPhotos")
        self.actionEditPhotosByFilter = QtWidgets.QAction(MainWindow)
        self.actionEditPhotosByFilter.setObjectName("actionEditPhotosByFilter")
        self.actionOpenPhotoSettings = QtWidgets.QAction(MainWindow)
        self.actionOpenPhotoSettings.setObjectName("actionOpenPhotoSettings")
        self.actionAddPhotos = QtWidgets.QAction(MainWindow)
        self.actionAddPhotos.setObjectName("actionAddPhotos")
        self.actionSavePhotoSettings = QtWidgets.QAction(MainWindow)
        self.actionSavePhotoSettings.setObjectName("actionSavePhotoSettings")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionUpdateEXIFDataForAllPhotos = QtWidgets.QAction(MainWindow)
        self.actionUpdateEXIFDataForAllPhotos.setObjectName("actionUpdateEXIFDataForAllPhotos")
        self.actionShowPhotoFilter = QtWidgets.QAction(MainWindow)
        self.actionShowPhotoFilter.setObjectName("actionShowPhotoFilter")
        self.actionHidePhotoFilter = QtWidgets.QAction(MainWindow)
        self.actionHidePhotoFilter.setObjectName("actionHidePhotoFilter")
        self.actionClearPhotoFilter = QtWidgets.QAction(MainWindow)
        self.actionClearPhotoFilter.setObjectName("actionClearPhotoFilter")
        self.actionClearStandardFilter = QtWidgets.QAction(MainWindow)
        self.actionClearStandardFilter.setObjectName("actionClearStandardFilter")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionClosePhotoSettings = QtWidgets.QAction(MainWindow)
        self.actionClosePhotoSettings.setObjectName("actionClosePhotoSettings")
        self.actionUS_States = QtWidgets.QAction(MainWindow)
        self.actionUS_States.setObjectName("actionUS_States")
        self.actionWorld_Countries = QtWidgets.QAction(MainWindow)
        self.actionWorld_Countries.setObjectName("actionWorld_Countries")
        self.actionWorld_Subregion_1 = QtWidgets.QAction(MainWindow)
        self.actionWorld_Subregion_1.setObjectName("actionWorld_Subregion_1")
        self.actionUS_Counties = QtWidgets.QAction(MainWindow)
        self.actionUS_Counties.setObjectName("actionUS_Counties")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionCreatePDF)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuReports.addAction(self.actionDateTotals)
        self.menuReports.addAction(self.actionLocationTotals)
        self.menuReports.addAction(self.actionCompareLists)
        self.menuReports.addAction(self.actionBigReport)
        self.menuWindows.addAction(self.actionTileWindows)
        self.menuWindows.addAction(self.actionCascade)
        self.menuWindows.addAction(self.actionCloseAllWindows)
        self.menuMap.addAction(self.actionMap)
        self.menuLists.addAction(self.actionSpecies)
        self.menuLists.addAction(self.actionLocations)
        self.menuLists.addAction(self.actionChecklists)
        self.menuLists.addAction(self.actionFamilies)
        self.menuLists.addAction(self.actionPhotos)
        self.menuAbout.addAction(self.actionAboutLapwing)
        self.menuFilter.addAction(self.actionShowStandardFilter)
        self.menuFilter.addAction(self.actionShowPhotoFilter)
        self.menuFilter.addAction(self.actionHideStandardFilter)
        self.menuFilter.addAction(self.actionHidePhotoFilter)
        self.menuFilter.addSeparator()
        self.menuFilter.addAction(self.actionClearAllFilters)
        self.menuFilter.addAction(self.actionClearStandardFilter)
        self.menuFilter.addAction(self.actionClearPhotoFilter)
        self.menuPhotos.addAction(self.actionOpenPhotoSettings)
        self.menuPhotos.addAction(self.actionClosePhotoSettings)
        self.menuPhotos.addAction(self.actionSavePhotoSettings)
        self.menuPhotos.addSeparator()
        self.menuPhotos.addAction(self.actionAddPhotos)
        self.menuPhotos.addAction(self.actionEditPhotosByFilter)
        self.menuPhotos.addAction(self.actionUpdateEXIFDataForAllPhotos)
        self.menuChoropleths.addAction(self.actionUS_States)
        self.menuChoropleths.addAction(self.actionUS_Counties)
        self.menuChoropleths.addAction(self.actionWorld_Countries)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuFilter.menuAction())
        self.menuBar.addAction(self.menuLists.menuAction())
        self.menuBar.addAction(self.menuMap.menuAction())
        self.menuBar.addAction(self.menuReports.menuAction())
        self.menuBar.addAction(self.menuPhotos.menuAction())
        self.menuBar.addAction(self.menuChoropleths.menuAction())
        self.menuBar.addAction(self.menuWindows.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionCreatePDF)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClearAllFilters)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSpecies)
        self.toolBar.addAction(self.actionLocations)
        self.toolBar.addAction(self.actionChecklists)
        self.toolBar.addAction(self.actionMap)
        self.toolBar.addAction(self.actionFamilies)
        self.toolBar.addAction(self.actionDateTotals)
        self.toolBar.addAction(self.actionLocationTotals)
        self.toolBar.addAction(self.actionCompareLists)
        self.toolBar.addAction(self.actionBigReport)
        self.toolBar.addAction(self.actionPhotos)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFind)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "eBird Analyzer"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuReports.setTitle(_translate("MainWindow", "Reports"))
        self.menuWindows.setTitle(_translate("MainWindow", "Windows"))
        self.menuMap.setTitle(_translate("MainWindow", "Map"))
        self.menuLists.setTitle(_translate("MainWindow", "Lists"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuFilter.setTitle(_translate("MainWindow", "Filter"))
        self.menuPhotos.setTitle(_translate("MainWindow", "Photos"))
        self.menuChoropleths.setTitle(_translate("MainWindow", "Choropleths"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dckFilter.setWindowTitle(_translate("MainWindow", "Standard Filter"))
        self.lblCountries_2.setText(_translate("MainWindow", "Region"))
        self.cboRegions.setToolTip(_translate("MainWindow", "Select a country to limit your search to one country\'s sightings."))
        self.lblCountries.setText(_translate("MainWindow", "Country"))
        self.cboCountries.setToolTip(_translate("MainWindow", "Select a country to limit your search to one country\'s sightings."))
        self.lblStates.setText(_translate("MainWindow", "State"))
        self.cboStates.setToolTip(_translate("MainWindow", "Select a state to limit your search to one state\'s sightings."))
        self.lblCounties.setText(_translate("MainWindow", "County"))
        self.cboCounties.setToolTip(_translate("MainWindow", "Select a countyto limit your search to one county\'s sightings."))
        self.lblLocations.setText(_translate("MainWindow", "Location"))
        self.cboLocations.setToolTip(_translate("MainWindow", "Select a location to limit your search to one location\'s sightings."))
        self.lblOrders.setText(_translate("MainWindow", "Order"))
        self.cboOrders.setToolTip(_translate("MainWindow", "Select an order to limit your search to sightings of one order."))
        self.lblFamilies.setText(_translate("MainWindow", "Familiy"))
        self.cboFamilies.setToolTip(_translate("MainWindow", "Select a family to limit your search to sightings of one family."))
        self.lblSpecies.setText(_translate("MainWindow", "Species"))
        self.cboSpecies.setToolTip(_translate("MainWindow", "Select a species to limit your search to sightings of one species."))
        self.lblCommonNameSearch.setText(_translate("MainWindow", "Name Search"))
        self.txtCommonNameSearch.setToolTip(_translate("MainWindow", "Enter text that must appear in the common name.  Prepend your text with s: to search the scientific name instead."))
        self.lblEndSeasonalRange_2.setText(_translate("MainWindow", "Date Options"))
        self.cboDateOptions.setToolTip(_translate("MainWindow", "Select a date option to limit your search."))
        self.lblStartDate.setText(_translate("MainWindow", "Start Date"))
        self.calStartDate.setToolTip(_translate("MainWindow", "Select a start date."))
        self.calStartDate.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.lblEndDate.setText(_translate("MainWindow", "End Date"))
        self.calEndDate.setToolTip(_translate("MainWindow", "Select an end date."))
        self.calEndDate.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.lblEndSeasonalRange_3.setText(_translate("MainWindow", "Seasonal Range Options"))
        self.cboSeasonalRangeOptions.setToolTip(_translate("MainWindow", "Select a seasonal range, such as a time of year."))
        self.lblStartSeasonalRange.setText(_translate("MainWindow", "Start Seasonal Range"))
        self.cboStartSeasonalRangeMonth.setToolTip(_translate("MainWindow", "Select the starting seasonal range\'s month."))
        self.cboStartSeasonalRangeDate.setToolTip(_translate("MainWindow", "Select the starting seasonal range\'s date."))
        self.lblEndSeasonalRange.setText(_translate("MainWindow", "End Seasonal Range"))
        self.cboEndSeasonalRangeMonth.setToolTip(_translate("MainWindow", "Select the ending seasonal range\'s month."))
        self.cboEndSeasonalRangeDate.setToolTip(_translate("MainWindow", "Select the ending seasonal range\'s date."))
        self.dckPhotoFilter.setWindowTitle(_translate("MainWindow", "Photo Filter"))
        self.lblSighting.setText(_translate("MainWindow", "Rating Range"))
        self.cboStartRatingRange.setToolTip(_translate("MainWindow", "Specify the lowest f-stop aperture for a range of apertures."))
        self.cboEndRatingRange.setToolTip(_translate("MainWindow", "Specify the highest f-stop aperture for a range of apertures."))
        self.lblSpeciesHasPhoto.setText(_translate("MainWindow", "Species"))
        self.cboSpeciesHasPhoto.setToolTip(_translate("MainWindow", "Specify whether a species must\n"
"have a photo attached for the other\n"
"filters\' circumstances.\n"
"(You don\'t need to set this\n"
"if you set other camera filters.)"))
        self.lblCamera.setText(_translate("MainWindow", "Camera"))
        self.cboCamera.setToolTip(_translate("MainWindow", "Specify a camera model."))
        self.lblLens.setText(_translate("MainWindow", "Lens"))
        self.cboLens.setToolTip(_translate("MainWindow", "Specify a lens model."))
        self.lblShutterSpeedRange.setText(_translate("MainWindow", "Shutter Speed Range"))
        self.cboStartShutterSpeedRange.setToolTip(_translate("MainWindow", "Specify the shortest shutter speed for a range of shutter speeds."))
        self.cboEndShutterSpeedRange.setToolTip(_translate("MainWindow", "Specify the longest shutter speed for a range of shutter speeds."))
        self.lblApertureRange.setText(_translate("MainWindow", "Aperture Range"))
        self.cboStartApertureRange.setToolTip(_translate("MainWindow", "Specify the lowest f-stop aperture for a range of apertures."))
        self.cboEndApertureRange.setToolTip(_translate("MainWindow", "Specify the highest f-stop aperture for a range of apertures."))
        self.lblFocalLengthRange.setText(_translate("MainWindow", "Focal Length Range"))
        self.cboStartFocalLengthRange.setToolTip(_translate("MainWindow", "Specify the shortest focal length for a range of focal lengths."))
        self.cboEndFocalLengthRange.setToolTip(_translate("MainWindow", "Specify the longest focal length for a range of focal lengths."))
        self.lblISORange.setText(_translate("MainWindow", "ISO Range"))
        self.cboStartIsoRange.setToolTip(_translate("MainWindow", "Specify the lowest ISO number for a range of ISO numbers."))
        self.cboEndIsoRange.setToolTip(_translate("MainWindow", "Specify the highest ISO number for a range of ISO numbers."))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionDateTotals.setText(_translate("MainWindow", "Date Totals"))
        self.actionLocationTotals.setText(_translate("MainWindow", "Location Totals"))
        self.actionTileWindows.setText(_translate("MainWindow", "Tile Windows"))
        self.actionCloseAllWindows.setText(_translate("MainWindow", "Close All Windows"))
        self.actionCompareLists.setText(_translate("MainWindow", "Compare Lists"))
        self.actionCascade.setText(_translate("MainWindow", "Cascade Windows"))
        self.actionSpecies.setText(_translate("MainWindow", "Species"))
        self.actionLocations.setText(_translate("MainWindow", "Locations"))
        self.actionChecklists.setText(_translate("MainWindow", "Checklists"))
        self.actionBigReport.setText(_translate("MainWindow", "Big Report"))
        self.actionBigReport.setToolTip(_translate("MainWindow", "Big Report"))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionFamilies.setText(_translate("MainWindow", "Families"))
        self.actionMap.setText(_translate("MainWindow", "Map"))
        self.actionCreatePDF.setText(_translate("MainWindow", "Create PDF"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionAboutLapwing.setText(_translate("MainWindow", "About Lapwing"))
        self.actionShowStandardFilter.setText(_translate("MainWindow", "Show standard filter"))
        self.actionHideStandardFilter.setText(_translate("MainWindow", "Hide standard filter"))
        self.actionHideStandardFilter.setToolTip(_translate("MainWindow", "Hide standard filter"))
        self.actionClearAllFilters.setText(_translate("MainWindow", "Clear all filters"))
        self.actionSetPhotoFolder.setText(_translate("MainWindow", "Set Photo Folder"))
        self.actionPhotos.setText(_translate("MainWindow", "Photos"))
        self.actionEditPhotosByFilter.setText(_translate("MainWindow", "Edit photos by filter..."))
        self.actionOpenPhotoSettings.setText(_translate("MainWindow", "Open photo settings file..."))
        self.actionAddPhotos.setText(_translate("MainWindow", "Add photos..."))
        self.actionSavePhotoSettings.setText(_translate("MainWindow", "Save photo settings file..."))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionUpdateEXIFDataForAllPhotos.setText(_translate("MainWindow", "Update EXIF data for all photos"))
        self.actionShowPhotoFilter.setText(_translate("MainWindow", "Show photo filter"))
        self.actionHidePhotoFilter.setText(_translate("MainWindow", "Hide photo filter"))
        self.actionClearPhotoFilter.setText(_translate("MainWindow", "Clear photo filter"))
        self.actionClearStandardFilter.setText(_translate("MainWindow", "Clear standard filters"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClosePhotoSettings.setText(_translate("MainWindow", "Close photo settings file"))
        self.actionUS_States.setText(_translate("MainWindow", "US States"))
        self.actionWorld_Countries.setText(_translate("MainWindow", "World Countries"))
        self.actionWorld_Subregion_1.setText(_translate("MainWindow", "World Subregion 1"))
        self.actionUS_Counties.setText(_translate("MainWindow", "US Counties"))
import icons_rc
