# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Compare.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmCompare(object):
    def setupUi(self, frmCompare):
        frmCompare.setObjectName("frmCompare")
        frmCompare.resize(800, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmCompare.sizePolicy().hasHeightForWidth())
        frmCompare.setSizePolicy(sizePolicy)
        frmCompare.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_compare.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmCompare.setWindowIcon(icon)
        self.scrollArea = QtWidgets.QScrollArea(frmCompare)
        self.scrollArea.setGeometry(QtCore.QRect(9, 9, 720, 292))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 720, 292))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cboListsLeft = QtWidgets.QComboBox(self.frame)
        self.cboListsLeft.setObjectName("cboListsLeft")
        self.verticalLayout_2.addWidget(self.cboListsLeft)
        self.lblLeftListOnly = QtWidgets.QLabel(self.frame)
        self.lblLeftListOnly.setObjectName("lblLeftListOnly")
        self.verticalLayout_2.addWidget(self.lblLeftListOnly)
        self.lstLeftOnly = QtWidgets.QListWidget(self.frame)
        self.lstLeftOnly.setObjectName("lstLeftOnly")
        self.verticalLayout_2.addWidget(self.lstLeftOnly)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnCompare = QtWidgets.QPushButton(self.frame_2)
        self.btnCompare.setObjectName("btnCompare")
        self.verticalLayout_3.addWidget(self.btnCompare)
        self.lblBothLists = QtWidgets.QLabel(self.frame_2)
        self.lblBothLists.setObjectName("lblBothLists")
        self.verticalLayout_3.addWidget(self.lblBothLists)
        self.lstBoth = QtWidgets.QListWidget(self.frame_2)
        self.lstBoth.setObjectName("lstBoth")
        self.verticalLayout_3.addWidget(self.lstBoth)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cboListsRight = QtWidgets.QComboBox(self.frame_3)
        self.cboListsRight.setObjectName("cboListsRight")
        self.verticalLayout_4.addWidget(self.cboListsRight)
        self.lblRightListOnly = QtWidgets.QLabel(self.frame_3)
        self.lblRightListOnly.setObjectName("lblRightListOnly")
        self.verticalLayout_4.addWidget(self.lblRightListOnly)
        self.lstRightOnly = QtWidgets.QListWidget(self.frame_3)
        self.lstRightOnly.setObjectName("lstRightOnly")
        self.verticalLayout_4.addWidget(self.lstRightOnly)
        self.horizontalLayout.addWidget(self.frame_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(frmCompare)
        QtCore.QMetaObject.connectSlotsByName(frmCompare)

    def retranslateUi(self, frmCompare):
        _translate = QtCore.QCoreApplication.translate
        frmCompare.setWindowTitle(_translate("frmCompare", "Compare Lists"))
        self.lblLeftListOnly.setText(_translate("frmCompare", "This List Only"))
        self.lstLeftOnly.setSortingEnabled(False)
        self.btnCompare.setText(_translate("frmCompare", "Compare"))
        self.lblBothLists.setText(_translate("frmCompare", "Species on Both Lists"))
        self.lstBoth.setSortingEnabled(False)
        self.lblRightListOnly.setText(_translate("frmCompare", "This List Only"))
        self.lstRightOnly.setSortingEnabled(False)

import icons_rc
