# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_Preferences.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmPreferences(object):
    def setupUi(self, frmPreferences):
        frmPreferences.setObjectName("frmPreferences")
        frmPreferences.resize(836, 382)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmPreferences.sizePolicy().hasHeightForWidth())
        frmPreferences.setSizePolicy(sizePolicy)
        frmPreferences.setMinimumSize(QtCore.QSize(200, 300))
        frmPreferences.setSizeIncrement(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_Yearbird_small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmPreferences.setWindowIcon(icon)
        self.grpStartupFolder = QtWidgets.QGroupBox(frmPreferences)
        self.grpStartupFolder.setGeometry(QtCore.QRect(10, 30, 828, 127))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpStartupFolder.sizePolicy().hasHeightForWidth())
        self.grpStartupFolder.setSizePolicy(sizePolicy)
        self.grpStartupFolder.setObjectName("grpStartupFolder")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grpStartupFolder)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chkStartupFolder = QtWidgets.QCheckBox(self.grpStartupFolder)
        self.chkStartupFolder.setObjectName("chkStartupFolder")
        self.verticalLayout_2.addWidget(self.chkStartupFolder)
        self.frame = QtWidgets.QFrame(self.grpStartupFolder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtStartupFolder = QtWidgets.QLineEdit(self.frame)
        self.txtStartupFolder.setObjectName("txtStartupFolder")
        self.horizontalLayout_2.addWidget(self.txtStartupFolder)
        self.btnSelectStartupFolder = QtWidgets.QPushButton(self.frame)
        self.btnSelectStartupFolder.setObjectName("btnSelectStartupFolder")
        self.horizontalLayout_2.addWidget(self.btnSelectStartupFolder)
        self.verticalLayout_2.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(frmPreferences)
        self.buttonBox.setGeometry(QtCore.QRect(10, 310, 166, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.grpPhotoDataFile = QtWidgets.QGroupBox(frmPreferences)
        self.grpPhotoDataFile.setGeometry(QtCore.QRect(10, 170, 811, 127))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpPhotoDataFile.sizePolicy().hasHeightForWidth())
        self.grpPhotoDataFile.setSizePolicy(sizePolicy)
        self.grpPhotoDataFile.setObjectName("grpPhotoDataFile")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.grpPhotoDataFile)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chkPhotoDataFile = QtWidgets.QCheckBox(self.grpPhotoDataFile)
        self.chkPhotoDataFile.setObjectName("chkPhotoDataFile")
        self.verticalLayout.addWidget(self.chkPhotoDataFile)
        self.frame_2 = QtWidgets.QFrame(self.grpPhotoDataFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtPhotoDataFile = QtWidgets.QLineEdit(self.frame_2)
        self.txtPhotoDataFile.setObjectName("txtPhotoDataFile")
        self.horizontalLayout.addWidget(self.txtPhotoDataFile)
        self.btnSelectPhotoDataFile = QtWidgets.QPushButton(self.frame_2)
        self.btnSelectPhotoDataFile.setObjectName("btnSelectPhotoDataFile")
        self.horizontalLayout.addWidget(self.btnSelectPhotoDataFile)
        self.verticalLayout.addWidget(self.frame_2)
        self.actionSetDateFilter = QtWidgets.QAction(frmPreferences)
        self.actionSetDateFilter.setObjectName("actionSetDateFilter")
        self.actionSetLocationFilter = QtWidgets.QAction(frmPreferences)
        self.actionSetLocationFilter.setObjectName("actionSetLocationFilter")
        self.actionSetFirstDateFilter = QtWidgets.QAction(frmPreferences)
        self.actionSetFirstDateFilter.setObjectName("actionSetFirstDateFilter")
        self.actionSetLastDateFilter = QtWidgets.QAction(frmPreferences)
        self.actionSetLastDateFilter.setObjectName("actionSetLastDateFilter")
        self.actionSetSpeciesFilter = QtWidgets.QAction(frmPreferences)
        self.actionSetSpeciesFilter.setObjectName("actionSetSpeciesFilter")
        self.actionSetCountryFilter = QtWidgets.QAction(frmPreferences)
        self.actionSetCountryFilter.setObjectName("actionSetCountryFilter")
        self.actionSetStateFilter = QtWidgets.QAction(frmPreferences)
        self.actionSetStateFilter.setObjectName("actionSetStateFilter")
        self.actionSetCountyFilter = QtWidgets.QAction(frmPreferences)
        self.actionSetCountyFilter.setObjectName("actionSetCountyFilter")

        self.retranslateUi(frmPreferences)
        QtCore.QMetaObject.connectSlotsByName(frmPreferences)

    def retranslateUi(self, frmPreferences):
        _translate = QtCore.QCoreApplication.translate
        frmPreferences.setWindowTitle(_translate("frmPreferences", "Preferences"))
        self.grpStartupFolder.setTitle(_translate("frmPreferences", "Startup Folder"))
        self.chkStartupFolder.setText(_translate("frmPreferences", "Set eBird data folder. At startup, Yearbird will open the most recent eBird file in the folder (e.g., your download folder)."))
        self.btnSelectStartupFolder.setText(_translate("frmPreferences", "Select"))
        self.grpPhotoDataFile.setTitle(_translate("frmPreferences", "Photo Data File"))
        self.chkPhotoDataFile.setText(_translate("frmPreferences", "Load photo data file at startup. (Only helpful if you have photos.)"))
        self.btnSelectPhotoDataFile.setText(_translate("frmPreferences", "Select"))
        self.actionSetDateFilter.setText(_translate("frmPreferences", "Set Filter to Date"))
        self.actionSetLocationFilter.setText(_translate("frmPreferences", "Set Filter to Location"))
        self.actionSetFirstDateFilter.setText(_translate("frmPreferences", "Set Filter to \"First\" Date"))
        self.actionSetLastDateFilter.setText(_translate("frmPreferences", "Set Filter to \"Last\" Date"))
        self.actionSetSpeciesFilter.setText(_translate("frmPreferences", "Set Filter to Species"))
        self.actionSetCountryFilter.setText(_translate("frmPreferences", "Set Filter to Country"))
        self.actionSetStateFilter.setText(_translate("frmPreferences", "Set Filter to State"))
        self.actionSetCountyFilter.setText(_translate("frmPreferences", "Set Filter to County"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmPreferences = QtWidgets.QWidget()
    ui = Ui_frmPreferences()
    ui.setupUi(frmPreferences)
    frmPreferences.show()
    sys.exit(app.exec_())

