# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_Families.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmFamilies(object):
    def setupUi(self, frmFamilies):
        frmFamilies.setObjectName("frmFamilies")
        frmFamilies.resize(780, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmFamilies.sizePolicy().hasHeightForWidth())
        frmFamilies.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_families.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmFamilies.setWindowIcon(icon)
        self.scrollArea = QtWidgets.QScrollArea(frmFamilies)
        self.scrollArea.setGeometry(QtCore.QRect(9, 9, 570, 377))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 570, 377))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblLocation = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLocation.sizePolicy().hasHeightForWidth())
        self.lblLocation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblLocation.setFont(font)
        self.lblLocation.setObjectName("lblLocation")
        self.verticalLayout_4.addWidget(self.lblLocation)
        self.lblDateRange = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateRange.sizePolicy().hasHeightForWidth())
        self.lblDateRange.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblDateRange.setFont(font)
        self.lblDateRange.setObjectName("lblDateRange")
        self.verticalLayout_4.addWidget(self.lblDateRange)
        self.lblDetails = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDetails.sizePolicy().hasHeightForWidth())
        self.lblDetails.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblDetails.setFont(font)
        self.lblDetails.setObjectName("lblDetails")
        self.verticalLayout_4.addWidget(self.lblDetails)
        self.tabFamilies = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabFamilies.setObjectName("tabFamilies")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblFamilies = QtWidgets.QLabel(self.frame)
        self.lblFamilies.setObjectName("lblFamilies")
        self.verticalLayout_2.addWidget(self.lblFamilies)
        self.lstFamilies = QtWidgets.QListWidget(self.frame)
        self.lstFamilies.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lstFamilies.setObjectName("lstFamilies")
        self.verticalLayout_2.addWidget(self.lstFamilies)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblSpecies = QtWidgets.QLabel(self.frame_2)
        self.lblSpecies.setObjectName("lblSpecies")
        self.verticalLayout_3.addWidget(self.lblSpecies)
        self.lstSpecies = QtWidgets.QListWidget(self.frame_2)
        self.lstSpecies.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lstSpecies.setObjectName("lstSpecies")
        self.verticalLayout_3.addWidget(self.lstSpecies)
        self.horizontalLayout.addWidget(self.frame_2)
        self.tabFamilies.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gvPieChart = QtWidgets.QGraphicsView(self.tab_2)
        self.gvPieChart.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gvPieChart.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.gvPieChart.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.gvPieChart.setObjectName("gvPieChart")
        self.horizontalLayout_2.addWidget(self.gvPieChart)
        self.tblPieChartLegend = QtWidgets.QTableWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblPieChartLegend.sizePolicy().hasHeightForWidth())
        self.tblPieChartLegend.setSizePolicy(sizePolicy)
        self.tblPieChartLegend.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tblPieChartLegend.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblPieChartLegend.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tblPieChartLegend.setLineWidth(0)
        self.tblPieChartLegend.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblPieChartLegend.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblPieChartLegend.setObjectName("tblPieChartLegend")
        self.tblPieChartLegend.setColumnCount(0)
        self.tblPieChartLegend.setRowCount(0)
        self.tblPieChartLegend.horizontalHeader().setVisible(False)
        self.tblPieChartLegend.horizontalHeader().setHighlightSections(False)
        self.tblPieChartLegend.verticalHeader().setVisible(False)
        self.tblPieChartLegend.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_2.addWidget(self.tblPieChartLegend)
        self.tabFamilies.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabFamilies)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.actionSetFamilyFilterToPieChartLegendFamily = QtWidgets.QAction(frmFamilies)
        self.actionSetFamilyFilterToPieChartLegendFamily.setObjectName("actionSetFamilyFilterToPieChartLegendFamily")
        self.actionSetFilterToFamily = QtWidgets.QAction(frmFamilies)
        self.actionSetFilterToFamily.setObjectName("actionSetFilterToFamily")
        self.actionSetFilterToSpecies = QtWidgets.QAction(frmFamilies)
        self.actionSetFilterToSpecies.setObjectName("actionSetFilterToSpecies")

        self.retranslateUi(frmFamilies)
        self.tabFamilies.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(frmFamilies)

    def retranslateUi(self, frmFamilies):
        _translate = QtCore.QCoreApplication.translate
        frmFamilies.setWindowTitle(_translate("frmFamilies", "Species Report"))
        self.lblLocation.setText(_translate("frmFamilies", "Location"))
        self.lblDateRange.setText(_translate("frmFamilies", "Date Range"))
        self.lblDetails.setText(_translate("frmFamilies", "Details Label"))
        self.lblFamilies.setText(_translate("frmFamilies", "Families"))
        self.lstFamilies.setSortingEnabled(False)
        self.lblSpecies.setText(_translate("frmFamilies", "Species"))
        self.lstSpecies.setSortingEnabled(False)
        self.tabFamilies.setTabText(self.tabFamilies.indexOf(self.tab), _translate("frmFamilies", "Families"))
        self.tblPieChartLegend.setSortingEnabled(True)
        self.tabFamilies.setTabText(self.tabFamilies.indexOf(self.tab_2), _translate("frmFamilies", "Pie Chart"))
        self.actionSetFamilyFilterToPieChartLegendFamily.setText(_translate("frmFamilies", "Set filter to family"))
        self.actionSetFilterToFamily.setText(_translate("frmFamilies", "Set filter to family"))
        self.actionSetFilterToSpecies.setText(_translate("frmFamilies", "Set filter to species"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmFamilies = QtWidgets.QWidget()
    ui = Ui_frmFamilies()
    ui.setupUi(frmFamilies)
    frmFamilies.show()
    sys.exit(app.exec_())

