# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Location.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmLocation(object):
    def setupUi(self, frmLocation):
        frmLocation.setObjectName("frmLocation")
        frmLocation.resize(884, 625)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmLocation.sizePolicy().hasHeightForWidth())
        frmLocation.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_location.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmLocation.setWindowIcon(icon)
        self.scrollArea = QtWidgets.QScrollArea(frmLocation)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 861, 611))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 861, 611))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblLocation = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLocation.sizePolicy().hasHeightForWidth())
        self.lblLocation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblLocation.setFont(font)
        self.lblLocation.setObjectName("lblLocation")
        self.verticalLayout.addWidget(self.lblLocation)
        self.lblFirstVisited = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFirstVisited.sizePolicy().hasHeightForWidth())
        self.lblFirstVisited.setSizePolicy(sizePolicy)
        self.lblFirstVisited.setObjectName("lblFirstVisited")
        self.verticalLayout.addWidget(self.lblFirstVisited)
        self.lblMostRecentlyVisited = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMostRecentlyVisited.sizePolicy().hasHeightForWidth())
        self.lblMostRecentlyVisited.setSizePolicy(sizePolicy)
        self.lblMostRecentlyVisited.setObjectName("lblMostRecentlyVisited")
        self.verticalLayout.addWidget(self.lblMostRecentlyVisited)
        self.tabLocation = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabLocation.setObjectName("tabLocation")
        self.tabDates = QtWidgets.QWidget()
        self.tabDates.setObjectName("tabDates")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabDates)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblSpecies = QtWidgets.QLabel(self.tabDates)
        self.lblSpecies.setObjectName("lblSpecies")
        self.verticalLayout_2.addWidget(self.lblSpecies)
        self.tblSpecies = QtWidgets.QTableWidget(self.tabDates)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblSpecies.sizePolicy().hasHeightForWidth())
        self.tblSpecies.setSizePolicy(sizePolicy)
        self.tblSpecies.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tblSpecies.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblSpecies.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblSpecies.setObjectName("tblSpecies")
        self.tblSpecies.setColumnCount(0)
        self.tblSpecies.setRowCount(0)
        self.tblSpecies.horizontalHeader().setVisible(False)
        self.tblSpecies.horizontalHeader().setHighlightSections(False)
        self.tblSpecies.verticalHeader().setVisible(False)
        self.tblSpecies.verticalHeader().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.tblSpecies)
        self.tabLocation.addTab(self.tabDates, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblDatesSeen = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDatesSeen.sizePolicy().hasHeightForWidth())
        self.lblDatesSeen.setSizePolicy(sizePolicy)
        self.lblDatesSeen.setObjectName("lblDatesSeen")
        self.verticalLayout_3.addWidget(self.lblDatesSeen)
        self.tblDates = QtWidgets.QTableWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblDates.sizePolicy().hasHeightForWidth())
        self.tblDates.setSizePolicy(sizePolicy)
        self.tblDates.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tblDates.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblDates.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblDates.setObjectName("tblDates")
        self.tblDates.setColumnCount(0)
        self.tblDates.setRowCount(0)
        self.tblDates.horizontalHeader().setVisible(False)
        self.tblDates.horizontalHeader().setHighlightSections(False)
        self.tblDates.verticalHeader().setVisible(False)
        self.tblDates.verticalHeader().setHighlightSections(False)
        self.verticalLayout_3.addWidget(self.tblDates)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblSpeciesSeen = QtWidgets.QLabel(self.frame_2)
        self.lblSpeciesSeen.setObjectName("lblSpeciesSeen")
        self.verticalLayout_4.addWidget(self.lblSpeciesSeen)
        self.lstSpecies = QtWidgets.QListWidget(self.frame_2)
        self.lstSpecies.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lstSpecies.setProperty("showDropIndicator", False)
        self.lstSpecies.setObjectName("lstSpecies")
        self.verticalLayout_4.addWidget(self.lstSpecies)
        self.horizontalLayout.addWidget(self.frame_2)
        self.tabLocation.addTab(self.tab, "")
        self.tabMap = QtWidgets.QWidget()
        self.tabMap.setObjectName("tabMap")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabMap)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabLocation.addTab(self.tabMap, "")
        self.verticalLayout.addWidget(self.tabLocation)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(frmLocation)
        self.tabLocation.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(frmLocation)

    def retranslateUi(self, frmLocation):
        _translate = QtCore.QCoreApplication.translate
        frmLocation.setWindowTitle(_translate("frmLocation", "Location Report"))
        self.lblLocation.setText(_translate("frmLocation", "Location Name"))
        self.lblFirstVisited.setText(_translate("frmLocation", "First Visited:"))
        self.lblMostRecentlyVisited.setText(_translate("frmLocation", "Most Recently Visited:"))
        self.lblSpecies.setText(_translate("frmLocation", "Species"))
        self.tblSpecies.setSortingEnabled(True)
        self.tabLocation.setTabText(self.tabLocation.indexOf(self.tabDates), _translate("frmLocation", "Species"))
        self.lblDatesSeen.setText(_translate("frmLocation", "Dates"))
        self.tblDates.setSortingEnabled(True)
        self.lblSpeciesSeen.setText(_translate("frmLocation", "Species Seen on Selected Date"))
        self.lstSpecies.setSortingEnabled(False)
        self.tabLocation.setTabText(self.tabLocation.indexOf(self.tab), _translate("frmLocation", "Dates"))
        self.tabLocation.setTabText(self.tabLocation.indexOf(self.tabMap), _translate("frmLocation", "Map"))

import icons_rc
